# Molecular Properties Computation: DuckDB vs PostgreSQL RDKit

This notebook compares two approaches for computing molecular properties from SwissLipids data:

1. **DuckDB + UDF**: Using DuckDB with custom RDKit UDF functions
2. **PostgreSQL RDKit Cartridge**: Using PostgreSQL with the RDKit cartridge extension

We'll compute multiple molecular properties including:
- Canonical SMILES
- Molecular weight
- LogP (partition coefficient)
- TPSA (topological polar surface area)
- Hydrogen bond donors/acceptors
- And more...

Processing **10,000 rows** from SwissLipids data for comprehensive performance testing.

In [1]:
import sys
import time
import json
from pathlib import Path
from datetime import UTC, datetime

import pandas as pd
import duckdb
import psycopg2
import sqlalchemy as sa
from sqlalchemy import create_engine, text

# Add project root to path
PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from omnipath_build.utils.rdkit_utils import register_rdkit_udf

## Setup: Load SwissLipids Sample Data

In [2]:
# Load the specific SwissLipids parquet file with 10,000 rows
bronze_path = PROJECT_ROOT / 'omnipath_build' / 'databases' / 'metabo' / 'bronze' / 'data' / 'swisslipids' / 'swisslipids_lipids' / '20250826_135637.parquet'

if not bronze_path.exists():
    raise FileNotFoundError(f'Parquet file not found: {bronze_path}')

print(f"Using bronze data: {bronze_path}")

# Load the data and process 10,000 unique SMILES
full_df = pd.read_parquet(bronze_path)
print(f"Total records in file: {len(full_df)}")

# Get unique SMILES for processing (10,000 rows)
unique_smiles = full_df['smiles'].dropna().str.strip()
unique_smiles = unique_smiles[unique_smiles != ''].drop_duplicates().head(10000)
print(f"Unique SMILES to process: {len(unique_smiles)}")

# Show some examples
print("\\nExample SMILES:")
for i, smiles in enumerate(unique_smiles.head(5)):
    print(f"{i+1}. {smiles}")

# Save the unique SMILES for later reference
smiles_list = unique_smiles.tolist()
print(f"\\nPrepared {len(smiles_list)} SMILES for molecular property computation")

Using bronze data: /Users/jschaul/Code/omnipath_build/omnipath_build/databases/metabo/bronze/data/swisslipids/swisslipids_lipids/20250826_135637.parquet
Total records in file: 779249
Unique SMILES to process: 10000
\nExample SMILES:
1. CC(C)CCCCCCCCC\C=C\[C@@H](O)[C@H](CO)NC([*])=O
2. CC(C)CCCCCCCCC\C=C\[C@@H](O)[C@@H]([NH3+])CO
3. CC(C)CCCCCCCCCCC[C@@H](O)[C@@H]([NH3+])CO
4. CC(C)CCCCCCCCC\C=C\[C@@H](O)[C@H](COP([O-])(=O)OCC[N+](C)(C)C)NC([*])=O
5. CCCCCCCCCCCCCCC[C@@H](O)[C@@H]([NH3+])CO
\nPrepared 10000 SMILES for molecular property computation

## Approach 1: DuckDB + UDF

Using DuckDB with custom RDKit UDF functions for comprehensive molecular property computation.

In [3]:
def compute_molecular_properties_duckdb(smiles_list, limit=None):
    """Compute comprehensive molecular properties using DuckDB + UDF."""
    conn = duckdb.connect(':memory:')
    register_rdkit_udf(conn)
    
    # Create a temporary table with input SMILES
    df_input = pd.DataFrame({'input_smiles': smiles_list})
    if limit:
        df_input = df_input.head(limit)
    
    conn.register('smiles_input', df_input)
    
    start_time = time.time()
    
    # Use the comprehensive rdkit_properties function
    result = conn.execute("""
        SELECT 
            input_smiles,
            rdkit_properties(input_smiles) AS properties_json,
            CURRENT_TIMESTAMP AS computed_at
        FROM smiles_input
        WHERE rdkit_properties(input_smiles) IS NOT NULL
        ORDER BY input_smiles
    """).df()
    
    # Parse the JSON properties into separate columns
    if len(result) > 0:
        properties_list = []
        for _, row in result.iterrows():
            props = json.loads(row['properties_json'])
            props['input_smiles'] = row['input_smiles']
            props['computed_at'] = row['computed_at']
            properties_list.append(props)
        
        result = pd.DataFrame(properties_list)
    
    end_time = time.time()
    
    conn.close()
    
    return result, end_time - start_time

# Test with DuckDB - full molecular properties
print("Computing molecular properties with DuckDB + UDF...")
duckdb_result, duckdb_time = compute_molecular_properties_duckdb(smiles_list)

print(f"DuckDB Results:")
print(f"  - Processing time: {duckdb_time:.2f} seconds")
print(f"  - Successful conversions: {len(duckdb_result)} / {len(smiles_list)}")
print(f"  - Success rate: {len(duckdb_result) / len(smiles_list) * 100:.1f}%")
print(f"  - Throughput: {len(duckdb_result) / duckdb_time:.1f} molecules/second")

# Show computed properties
if len(duckdb_result) > 0:
    print("\\nMolecular properties computed:")
    property_columns = [col for col in duckdb_result.columns if col not in ['input_smiles', 'computed_at']]
    print(f"  - {', '.join(property_columns)}")
    
    print("\\nSample results:")
    display_cols = ['input_smiles', 'canonical_smiles', 'molecular_weight', 'logp', 'tpsa']
    display(duckdb_result[display_cols].head())
    
    # Show summary statistics
    print("\\nProperty Statistics:")
    numeric_props = ['molecular_weight', 'exact_mass', 'logp', 'tpsa', 'hbd', 'hba', 'rotatable_bonds', 'heavy_atoms']
    summary_stats = duckdb_result[numeric_props].describe()
    display(summary_stats.round(2))

Computing molecular properties with DuckDB + UDF...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

DuckDB Results:
  - Processing time: 19.13 seconds
  - Successful conversions: 10000 / 10000
  - Success rate: 100.0%
  - Throughput: 522.7 molecules/second
\nMolecular properties computed:
  - canonical_smiles, inchi, inchikey, formula, molecular_weight, exact_mass, tpsa, logp, hbd, hba, rotatable_bonds, aromatic_rings, heavy_atoms
\nSample results:

,input_smiles,canonical_smiles,molecular_weight,logp,tpsa
0,C(=C/CCCCCCCCCCCCC)[C@@H](O)[C@@H](NC(=O)*)CO[...,*C(=O)N[C@@H](CO[C@@H]1O[C@H](CO)[C@H](O)[C@H]...,488.642,2.0486,148.71
1,C(CCCCCCCCCC(C(=O)[H])O)CCCC,CCCCCCCCCCCCCCC(O)C=O,256.430,4.6374,37.30
2,C(CO)(COP([O-])(=O)[O-])=O,O=C(CO)COP(=O)([O-])[O-],168.041,-2.6069,109.72
3,C12C(C3C(C(CC3)*)(C)CC1)CCC4C2(CCC(C4)OC(*)=O)C,*C(=O)OC1CCC2(C)C(CCC3C4CCC(*)C4(C)CCC32)C1,302.458,5.4214,26.30
4,CC(/C=CC=C(C)C=CC1=C(C)CCCC1(C)C)=CCO,CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=CCO,286.459,5.5103,20.23

\nProperty Statistics:

,molecular_weight,exact_mass,logp,tpsa,hbd,hba,rotatable_bonds,heavy_atoms
count,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00
mean,884.34,883.73,11.63,158.01,0.83,9.37,43.94,61.42
std,194.57,194.42,5.02,48.03,1.03,2.48,11.62,13.95
min,17.01,17.00,-12.66,0.00,0.00,0.00,0.00,1.00
25%,788.14,787.61,8.50,111.19,0.00,8.00,38.00,54.00
50%,901.28,900.67,11.77,178.96,1.00,10.00,45.00,62.00
75%,1012.58,1011.86,15.06,178.96,1.00,10.00,52.00,70.00
max,1596.61,1595.68,25.76,691.79,23.00,39.00,74.00,110.00

## Approach 2: PostgreSQL RDKit Cartridge

Using PostgreSQL with the RDKit cartridge extension for comprehensive molecular property computation.

In [4]:
def compute_molecular_properties_postgres(smiles_list, limit=None):
    """Compute comprehensive molecular properties using PostgreSQL RDKit cartridge."""
    # Connection parameters (adjust as needed)
    connection_string = "postgresql://postgres:postgres@localhost:5436/metabo"
    
    try:
        engine = create_engine(connection_string)
        
        with engine.connect() as conn:
            # Check if RDKit extension is available
            try:
                conn.execute(text("CREATE EXTENSION IF NOT EXISTS rdkit"))
                print("RDKit extension loaded successfully")
            except Exception as e:
                print(f"Warning: Could not load RDKit extension: {e}")
                return None, 0
            
            # Create temporary table
            conn.execute(text("""
                DROP TABLE IF EXISTS temp_smiles_input;
                CREATE TEMP TABLE temp_smiles_input (
                    id SERIAL PRIMARY KEY,
                    input_smiles TEXT,
                    mol MOL
                );
            """))
            
            # Insert SMILES data and convert to mol objects
            smiles_subset = smiles_list[:limit] if limit else smiles_list
            
            # Batch insert for better performance with proper escaping
            batch_size = 1000
            for i in range(0, len(smiles_subset), batch_size):
                batch = smiles_subset[i:i + batch_size]
                
                # Insert one by one to handle problematic SMILES
                for smiles in batch:
                    try:
                        conn.execute(text("""
                            INSERT INTO temp_smiles_input (input_smiles, mol) 
                            VALUES (:smiles, mol_from_smiles(:smiles))
                        """), {'smiles': smiles})
                    except:
                        # Skip problematic SMILES
                        continue
            
            conn.commit()
            
            start_time = time.time()
            
            # Compute comprehensive molecular properties using correct RDKit function names
            result = conn.execute(text("""
                SELECT 
                    input_smiles,
                    mol_to_smiles(mol) AS canonical_smiles,
                    mol_inchi(mol) AS inchi,
                    mol_inchikey(mol) AS inchikey,
                    mol_formula(mol) AS formula,
                    mol_amw(mol) AS molecular_weight,
                    mol_exactmw(mol) AS exact_mass,
                    mol_tpsa(mol) AS tpsa,
                    mol_logp(mol) AS logp,
                    mol_hbd(mol) AS hbd,
                    mol_hba(mol) AS hba,
                    mol_numrotatablebonds(mol) AS rotatable_bonds,
                    mol_numaromaticrings(mol) AS aromatic_rings,
                    mol_numheavyatoms(mol) AS heavy_atoms,
                    NOW() AS computed_at
                FROM temp_smiles_input
                WHERE mol IS NOT NULL
                ORDER BY input_smiles
            """))
            
            result_df = pd.DataFrame(result.fetchall(), columns=result.keys())
            end_time = time.time()
            
            return result_df, end_time - start_time
            
    except Exception as e:
        print(f"PostgreSQL connection error: {e}")
        print("Make sure PostgreSQL is running with: docker-compose up -d")
        return None, 0

# Test with PostgreSQL - full molecular properties
print("Computing molecular properties with PostgreSQL RDKit cartridge...")
postgres_result, postgres_time = compute_molecular_properties_postgres(smiles_list)

if postgres_result is not None:
    print(f"PostgreSQL Results:")
    print(f"  - Processing time: {postgres_time:.2f} seconds")
    print(f"  - Successful conversions: {len(postgres_result)} / {len(smiles_list)}")
    print(f"  - Success rate: {len(postgres_result) / len(smiles_list) * 100:.1f}%")
    print(f"  - Throughput: {len(postgres_result) / postgres_time:.1f} molecules/second")
    
    # Show computed properties
    if len(postgres_result) > 0:
        print("\\nMolecular properties computed:")
        property_columns = [col for col in postgres_result.columns if col not in ['input_smiles', 'computed_at']]
        print(f"  - {', '.join(property_columns)}")
        
        print("\\nSample results:")
        display_cols = ['input_smiles', 'canonical_smiles', 'molecular_weight', 'logp', 'tpsa']
        display(postgres_result[display_cols].head())
        
        # Show summary statistics
        print("\\nProperty Statistics:")
        numeric_props = ['molecular_weight', 'exact_mass', 'logp', 'tpsa', 'hbd', 'hba', 'rotatable_bonds', 'heavy_atoms']
        summary_stats = postgres_result[numeric_props].describe()
        display(summary_stats.round(2))
else:
    print("PostgreSQL test failed - check database connection and RDKit extension")

Computing molecular properties with PostgreSQL RDKit cartridge...
RDKit extension loaded successfully
PostgreSQL Results:
  - Processing time: 7.38 seconds
  - Successful conversions: 10000 / 10000
  - Success rate: 100.0%
  - Throughput: 1354.8 molecules/second
\nMolecular properties computed:
  - canonical_smiles, inchi, inchikey, formula, molecular_weight, exact_mass, tpsa, logp, hbd, hba, rotatable_bonds, aromatic_rings, heavy_atoms
\nSample results:

,input_smiles,canonical_smiles,molecular_weight,logp,tpsa
0,C12C(C3C(C(CC3)*)(C)CC1)CCC4C2(CCC(C4)OC(*)=O)C,*C(=O)OC1CCC2(C)C(CCC3C4CCC(*)C4(C)CCC32)C1,302.458,5.42140,26.30
1,Cc1cc2C(=O)C=C3C(C)(C)[C@@H](O)CC[C@]3(C)c2cc1O,Cc1cc2c(cc1O)[C@@]1(C)CC[C@H](O)C(C)(C)C1=CC2=O,286.371,3.26192,57.53
2,CC(C=CC1=C(C)CCCC1(C)C)=C/C=C/C(C)=C/C1OC1C=C(...,CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=CC1OC1/C=C(C)...,552.887,11.81700,12.53
3,CC(C=CC1=C(C)CCCC1(C)C)=C/C=C/C(C)=C/C(O)C(O)C...,CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=CC(O)C(O)/C=C...,570.902,10.77140,40.46
4,CC(C=CC=C(C)C=CC1=C(C)CCCC1(C)C)=C/C=C/C=C(C)/...,CC(C=CC1=C(C)CCCC1(C)C)=CC=CC(C)=C/C=C/C=C(C)/...,536.888,12.60580,0.00

\nProperty Statistics:

,molecular_weight,exact_mass,logp,tpsa,hbd,hba,rotatable_bonds,heavy_atoms
count,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00
mean,884.34,883.73,11.63,158.01,2.14,10.34,43.94,61.42
std,194.57,194.42,5.02,48.03,1.60,2.58,11.62,13.95
min,17.01,17.00,-12.66,0.00,0.00,0.00,0.00,1.00
25%,788.14,787.61,8.50,111.19,0.00,9.00,38.00,54.00
50%,901.28,900.67,11.77,178.96,3.00,11.00,45.00,62.00
75%,1012.58,1011.86,15.06,178.96,3.00,11.00,52.00,70.00
max,1596.61,1595.68,25.76,691.79,23.00,43.00,74.00,110.00

## Performance and Property Comparison

In [5]:
if postgres_result is not None and len(duckdb_result) > 0 and len(postgres_result) > 0:
    # Create comprehensive comparison summary
    comparison_data = {
        'Metric': [
            'Processing Time (seconds)',
            'Successful Conversions',
            'Success Rate (%)',
            'Throughput (molecules/second)',
            'Properties Computed'
        ],
        'DuckDB + UDF': [
            f"{duckdb_time:.2f}",
            f"{len(duckdb_result)}",
            f"{len(duckdb_result) / len(smiles_list) * 100:.1f}",
            f"{len(duckdb_result) / duckdb_time:.1f}",
            f"{len([col for col in duckdb_result.columns if col not in ['input_smiles', 'computed_at']])}"
        ],
        'PostgreSQL RDKit': [
            f"{postgres_time:.2f}",
            f"{len(postgres_result)}",
            f"{len(postgres_result) / len(smiles_list) * 100:.1f}",
            f"{len(postgres_result) / postgres_time:.1f}" if postgres_time > 0 else "N/A",
            f"{len([col for col in postgres_result.columns if col not in ['input_smiles', 'computed_at']])}"
        ]
    }
    
    comparison_df = pd.DataFrame(comparison_data)
    print("Performance Comparison:")
    display(comparison_df)
    
    # Compare property consistency for key molecular descriptors
    print("\\n" + "="*60)
    print("PROPERTY CONSISTENCY ANALYSIS")
    print("="*60)
    
    # Merge results for comparison
    merged = duckdb_result[['input_smiles', 'canonical_smiles', 'molecular_weight', 'logp', 'tpsa']].merge(
        postgres_result[['input_smiles', 'canonical_smiles', 'molecular_weight', 'logp', 'tpsa']],
        on='input_smiles',
        suffixes=('_duckdb', '_postgres')
    )
    
    if len(merged) > 0:
        print(f"Common successful conversions: {len(merged)}")
        
        # Compare key properties
        properties_to_compare = ['canonical_smiles', 'molecular_weight', 'logp', 'tpsa']
        
        for prop in properties_to_compare:
            duckdb_col = f"{prop}_duckdb"
            postgres_col = f"{prop}_postgres"
            
            if prop == 'canonical_smiles':
                # String comparison for SMILES
                matches = merged[duckdb_col] == merged[postgres_col]
                match_rate = matches.sum() / len(matches) * 100
                print(f"\\n{prop.upper()}:")
                print(f"  - Exact matches: {matches.sum()} / {len(matches)} ({match_rate:.1f}%)")
                
                if not matches.all():
                    print(f"  - Examples of differences:")
                    differences = merged[~matches][['input_smiles', duckdb_col, postgres_col]].head(3)
                    for _, row in differences.iterrows():
                        print(f"    {row['input_smiles'][:30]}...")
                        print(f"    DuckDB:  {row[duckdb_col]}")
                        print(f"    PostgreSQL: {row[postgres_col]}")
                        print()
            else:
                # Numeric comparison with tolerance
                diff = abs(merged[duckdb_col] - merged[postgres_col])
                tolerance = 0.01  # 1% tolerance
                relative_diff = diff / abs(merged[duckdb_col] + 1e-10)  # Avoid division by zero
                close_matches = relative_diff <= tolerance
                
                print(f"\\n{prop.upper()}:")
                print(f"  - Close matches (±{tolerance*100}%): {close_matches.sum()} / {len(close_matches)} ({close_matches.sum()/len(close_matches)*100:.1f}%)")
                print(f"  - Mean absolute difference: {diff.mean():.4f}")
                print(f"  - Max absolute difference: {diff.max():.4f}")
                
                if not close_matches.all():
                    worst_diff_idx = diff.idxmax()
                    worst_case = merged.loc[worst_diff_idx]
                    print(f"  - Worst case difference:")
                    print(f"    SMILES: {worst_case['input_smiles'][:30]}...")
                    print(f"    DuckDB: {worst_case[duckdb_col]:.4f}")
                    print(f"    PostgreSQL: {worst_case[postgres_col]:.4f}")
        
        # Statistical comparison of key properties
        print("\\n" + "="*60)
        print("STATISTICAL COMPARISON")
        print("="*60)
        
        stats_comparison = pd.DataFrame({
            'Property': [],
            'DuckDB_Mean': [],
            'PostgreSQL_Mean': [],
            'DuckDB_Std': [],
            'PostgreSQL_Std': [],
            'Correlation': []
        })
        
        numeric_props = ['molecular_weight', 'logp', 'tpsa']
        for prop in numeric_props:
            duckdb_col = f"{prop}_duckdb"
            postgres_col = f"{prop}_postgres"
            
            correlation = merged[duckdb_col].corr(merged[postgres_col])
            
            new_row = pd.DataFrame({
                'Property': [prop],
                'DuckDB_Mean': [merged[duckdb_col].mean()],
                'PostgreSQL_Mean': [merged[postgres_col].mean()],
                'DuckDB_Std': [merged[duckdb_col].std()],
                'PostgreSQL_Std': [merged[postgres_col].std()],
                'Correlation': [correlation]
            })
            stats_comparison = pd.concat([stats_comparison, new_row], ignore_index=True)
        
        display(stats_comparison.round(4))
        
    else:
        print("No common results found between the two approaches")

else:
    print("Cannot perform detailed comparison - one or both approaches failed")

Performance Comparison:

                          Metric DuckDB + UDF PostgreSQL RDKit
0      Processing Time (seconds)        19.13             7.38
1         Successful Conversions        10000            10000
2               Success Rate (%)        100.0            100.0
3  Throughput (molecules/second)        522.7           1354.8
4            Properties Computed           13               13

\n============================================================
PROPERTY CONSISTENCY ANALYSIS
============================================================
Common successful conversions: 10000
\nCANONICAL_SMILES:
  - Exact matches: 10000 / 10000 (100.0%)
\nMOLECULAR_WEIGHT:
  - Close matches (±1.0%): 10000 / 10000 (100.0%)
  - Mean absolute difference: 0.0000
  - Max absolute difference: 0.0000
\nLOGP:
  - Close matches (±1.0%): 10000 / 10000 (100.0%)
  - Mean absolute difference: 0.0000
  - Max absolute difference: 0.0000
\nTPSA:
  - Close matches (±1.0%): 10000 / 10000 (100.0%)
  - Mean absolute difference: 0.0000
  - Max absolute difference: 0.0000
\n============================================================
STATISTICAL COMPARISON
============================================================

,Property,DuckDB_Mean,PostgreSQL_Mean,DuckDB_Std,PostgreSQL_Std,Correlation
0,molecular_weight,884.3356,884.3356,194.5716,194.5716,1.0
1,logp,11.6273,11.6273,5.0240,5.0240,1.0
2,tpsa,158.0093,158.0093,48.0278,48.0278,1.0

# Test scalability with different batch sizes
batch_sizes = [100, 500, 1000, 2500] if len(smiles_list) >= 2500 else [100, 500, len(smiles_list)]
batch_results = []

print("="*60)
print("SCALABILITY TESTING")
print("="*60)

for batch_size in batch_sizes:
    print(f"\\nTesting batch size: {batch_size}")
    
    # DuckDB test
    _, duckdb_batch_time = compute_molecular_properties_duckdb(smiles_list, limit=batch_size)
    
    # PostgreSQL test (if available)
    if postgres_result is not None:
        _, postgres_batch_time = compute_molecular_properties_postgres(smiles_list, limit=batch_size)
    else:
        postgres_batch_time = None
    
    batch_results.append({
        'Batch_Size': batch_size,
        'DuckDB_Time_s': f"{duckdb_batch_time:.2f}",
        'PostgreSQL_Time_s': f"{postgres_batch_time:.2f}" if postgres_batch_time else "N/A",
        'DuckDB_Throughput': f"{batch_size / duckdb_batch_time:.1f}",
        'PostgreSQL_Throughput': f"{batch_size / postgres_batch_time:.1f}" if postgres_batch_time else "N/A",
        'DuckDB_Speed_Ratio': f"{1.0:.2f}",
        'PostgreSQL_Speed_Ratio': f"{duckdb_batch_time / postgres_batch_time:.2f}" if postgres_batch_time else "N/A"
    })

batch_df = pd.DataFrame(batch_results)
print("\\nScalability Results:")
display(batch_df)

# Plot performance if both approaches worked
if postgres_result is not None and len(batch_results) > 1:
    import matplotlib.pyplot as plt
    
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
    
    # Processing time vs batch size
    batch_sizes_plot = [int(r['Batch_Size']) for r in batch_results]
    duckdb_times = [float(r['DuckDB_Time_s']) for r in batch_results]
    postgres_times = [float(r['PostgreSQL_Time_s']) if r['PostgreSQL_Time_s'] != 'N/A' else None for r in batch_results]
    
    ax1.plot(batch_sizes_plot, duckdb_times, 'o-', label='DuckDB + UDF', linewidth=2, markersize=8)
    if all(t is not None for t in postgres_times):
        ax1.plot(batch_sizes_plot, postgres_times, 's-', label='PostgreSQL RDKit', linewidth=2, markersize=8)
    ax1.set_xlabel('Batch Size')
    ax1.set_ylabel('Processing Time (seconds)')
    ax1.set_title('Processing Time vs Batch Size')
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # Throughput vs batch size
    duckdb_throughput = [float(r['DuckDB_Throughput']) for r in batch_results]
    postgres_throughput = [float(r['PostgreSQL_Throughput']) if r['PostgreSQL_Throughput'] != 'N/A' else None for r in batch_results]
    
    ax2.plot(batch_sizes_plot, duckdb_throughput, 'o-', label='DuckDB + UDF', linewidth=2, markersize=8)
    if all(t is not None for t in postgres_throughput):
        ax2.plot(batch_sizes_plot, postgres_throughput, 's-', label='PostgreSQL RDKit', linewidth=2, markersize=8)
    ax2.set_xlabel('Batch Size')
    ax2.set_ylabel('Throughput (molecules/second)')
    ax2.set_title('Throughput vs Batch Size')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.show()

In [6]:
# Test different batch sizes
batch_sizes = [10, 50, 100, 500, 1000,2000, 5000] if len(unique_smiles) >= 500 else [10, 50, len(unique_smiles)]
batch_results = []

for batch_size in batch_sizes:
    print(f"\nTesting batch size: {batch_size}")
    
    # DuckDB test 
    _, duckdb_batch_time = compute_molecular_properties_duckdb(
        unique_smiles.tolist(), limit=batch_size
    )
    
    # PostgreSQL test (if available)
    if postgres_result is not None:
        _, postgres_batch_time = compute_molecular_properties_postgres(
            unique_smiles.tolist(), limit=batch_size
        )
    else:
        postgres_batch_time = None
    
    batch_results.append({
        'Batch Size': batch_size,
        'DuckDB Time (s)': f"{duckdb_batch_time:.2f}",
        'PostgreSQL Time (s)': f"{postgres_batch_time:.2f}" if postgres_batch_time else "N/A",
        'DuckDB Throughput': f"{batch_size / duckdb_batch_time:.1f}",
        'PostgreSQL Throughput': f"{batch_size / postgres_batch_time:.1f}" if postgres_batch_time else "N/A"
    })

batch_df = pd.DataFrame(batch_results)
print("\nBatch Processing Results:")
display(batch_df)

Testing batch size: 10
RDKit extension loaded successfully

Testing batch size: 50
RDKit extension loaded successfully

Testing batch size: 100
RDKit extension loaded successfully

Testing batch size: 500
RDKit extension loaded successfully

Testing batch size: 1000
RDKit extension loaded successfully

Testing batch size: 2000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

RDKit extension loaded successfully

Testing batch size: 5000

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

RDKit extension loaded successfully

Batch Processing Results:

,Batch Size,DuckDB Time (s),PostgreSQL Time (s),DuckDB Throughput,PostgreSQL Throughput
0,10,0.01,0.01,790.0,1561.1
1,50,0.06,0.03,773.3,1696.9
2,100,0.13,0.05,745.1,1901.0
3,500,0.77,0.26,646.5,1888.9
4,1000,1.62,0.55,616.4,1819.2
5,2000,3.96,1.38,505.3,1446.6
6,5000,10.02,3.67,498.9,1363.1

## Conclusions and Recommendations

### Key Findings from 10,000 Molecule Analysis:

**Performance Comparison:**
- **DuckDB + UDF**: Optimized for analytical workloads with built-in parallelization
- **PostgreSQL RDKit**: Full-featured chemical database with rich RDKit integration

**Property Coverage:**
Both approaches compute comprehensive molecular properties:
- **Identifiers**: Canonical SMILES, InChI, InChIKey
- **Basic Properties**: Molecular weight, exact mass, formula
- **Drug-like Properties**: LogP, TPSA, H-bond donors/acceptors
- **Structural Features**: Rotatable bonds, aromatic rings, heavy atoms

### Detailed Analysis:

#### DuckDB + UDF Approach:
**Pros:**
- Self-contained, no external database required
- Excellent integration with pandas/Python data science stack
- Built-in columnar analytics and aggregations
- Easy to distribute and reproduce
- Single JSON function returns all properties efficiently

**Cons:**
- Custom UDF implementation required
- Limited to single-node processing
- Less mature chemical database features

#### PostgreSQL RDKit Cartridge:
**Pros:**
- Native RDKit integration with full chemical functionality
- Mature and extensively tested in production
- Support for chemical indexing, similarity searches, substructure queries
- Multi-user, concurrent access
- Rich ecosystem of chemical extensions

**Cons:**
- Requires PostgreSQL server infrastructure
- Network overhead for database connections
- More complex deployment and maintenance
- Batch insertion can be slower for large datasets

### Use Case Recommendations:

**Choose DuckDB + UDF when:**
- Performing analytical queries on molecular data
- Working in Jupyter/Python data science environments
- Need embedded processing without server infrastructure
- Processing large datasets with columnar analytics
- Batch processing molecular property calculation

**Choose PostgreSQL RDKit when:**
- Building production chemical databases
- Need chemical similarity/substructure searches
- Require multi-user concurrent access
- Want mature chemical database features
- Building web applications with chemical data

### Performance Insights:
The scalability tests reveal how each approach handles increasing data volumes, helping you choose based on your expected workload size and processing patterns.